# Generated by Django 4.1 on 2022-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog_article_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_title", models.CharField(max_length=300)),
                ("article_urls", models.CharField(max_length=300)),
                ("image_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "links_image",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "publisheddate",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("category", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
