# Generated by Django 4.1 on 2022-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_article_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_article_data",
            name="publisheddate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
